@url = http://localhost:3000

### TEST VALIDATOR
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "inisangatrahasia"
}

### GET ENV
GET {{url}}/env 