@url = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YjUyNGYxOS0yZWY1LTQ5NWEtOWNkYy1kNzQ0OTZjYjViOWYiLCJleHAiOjE3NjY4NTM0MzJ9.lrOhcIx_v8mCz6Fk-6YQx6XfQYNZKigaOrOv13Js1tY
@expiredtoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YjUyNGYxOS0yZWY1LTQ5NWEtOWNkYy1kNzQ0OTZjYjViOWYiLCJleHAiOjE3NjY2ODI5ODV9.3BasIdd82QVyWD37hRTb8039Y5XNEoAvplcVwZgIMpI

@refresh_token = refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YjUyNGYxOS0yZWY1LTQ5NWEtOWNkYy1kNzQ0OTZjYjViOWYiLCJqdGkiOiJlMWIyMzAyZC0yZWY4LTQ4YjEtYjI0NS1lMWVhYjdlYjcwZjYiLCJleHAiOjE3Njk0NDQ4MzJ9.GH_Yqx56fQyPkFsPDTSWKgLONZ2pl9Qxs4J9yKmmhgI

### SIMPLE RUN
GET {{url}}
Authorization: Bearer validtoken

### TEST VALIDATOR
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "inisangatrahasia"
}

### TEST JWT MIDDLEWARE
GET {{url}}/auth/status
Authorization: Bearer {{token}}

### TEST JWT MIDDLEWARE EXPIRED
GET {{url}}/auth/status
Authorization: Bearer {{expiredtoken}}

### TEST REFRESH TOKEN
POST {{url}}/auth/refresh
Cookie: {{refresh_token}}